## <span style="color:blue">Problem Set 3</span>

1. If you **hard-code a solution you will 0 points** for the respective problem. You need to use code to arrive at a solution. 
2. **Use only syntax covered in the Learning Units to date.**  Using any other syntax results in 0 points for the problem.

### Problem 1

In the cell below, write code that iterates over the string `myStr` and does the following:
* print each character
* count the number of characters and store the result the variable `cntChars`
* print the variable `myStr` and `cntChars` with an appropriate label as shown below in Expected Output

In [20]:
for myStr in "MICHIGAN":
    print (myStr)
myStr = 'MICHIGAN'
cntChars = 0
for ch in myStr:
    cntChars = cntChars + 1
print ("The number of characters in MICHIGAN is",(cntChars))



M
I
C
H
I
G
A
N
The number of characters in MICHIGAN is 8


Expected Output:
```
M
I
C
H
I
G
A
N
The number of characters in MICHIGAN is 8
```

### Problem 2

In the cell below, write **one** loop that iterates over the list `mixedList` and does the following:
* print each element along with the element's type
* accumulatively count the number of elements and store the result in the variable `cntList`
* print `cntList` preceded by an appropriate label as shown below

In [27]:
mixedList = ["hello", 2, 4, 6.0, 7.5, 234352354, 
             "the end", "", 99, type, tuple, print]
for amixedList in mixedList:
    print(amixedList, type)
cntList = 0
for ch in mixedList:
    cntList = cntList + 1
print("The number of elements in the list is", cntList)


hello <class 'type'>
2 <class 'type'>
4 <class 'type'>
6.0 <class 'type'>
7.5 <class 'type'>
234352354 <class 'type'>
the end <class 'type'>
 <class 'type'>
99 <class 'type'>
<class 'type'> <class 'type'>
<class 'tuple'> <class 'type'>
<built-in function print> <class 'type'>
The number of elements in the list is 12


Expected Output:
```
hello <class 'str'>
2 <class 'int'>
4 <class 'int'>
6.0 <class 'float'>
7.5 <class 'float'>
234352354 <class 'int'>
the end <class 'str'>
 <class 'str'>
99 <class 'int'>
<class 'type'> <class 'type'>
<class 'tuple'> <class 'type'>
<built-in function print> <class 'builtin_function_or_method'>
The number of elements in the list is 12
```

### Problem 3

Write code that iterates over to the string `sentence` and does the following:
* count the number of characters using the variable `numChars`
* count the number of vowels using the variable `numVowels` (a character is a vowel if it  is included in the `vowels` tuple)
* print the variables `numChars` and `numVowels` preceded by appropriate labels as shown below

DO NOT use the built-in **`len()`** function to solve the problem. You may only use `len()` to confirm that your solution is correct.

In [30]:
sentence = "The quick brown rhino jumped over the extremely lazy fox."
vowels = ('a','e','i','o','u')

numChars = 0
for ch in sentence:
    numChars = numChars + 1
print ("The number of characters is",(numChars))

numVowels = 0
for ch in sentence:
    if ch in vowels:
        numVowels = numVowels + 1
print ("The number of vowels is",(numVowels))


The number of characters is 57
The number of vowels is 16


Expected Output:
```
The number of characters is 57
The number of vowels is 16
```

### Problem 4

Write code that does the following:
1. Create a list called `words` from the words in the string `sentence`.
2. Iterate over `words` and ...
    1. Populate a list called `wordLens` with the length of each element in `words`.
    2. Accumlatively count the number of words in `words` and store in the variable `numWords`.
    3. Print each word along with its length.

Use **one** loop to solve this problem. Make use of the built-in **`len()`** and **`split()`** functions.

Print the `wordLens` and `numWords` as shown below.

In [105]:
sentence = "The quick brown rhino jumped over the extremely lazy fox"
words = sentence.split (' ')
numWords = len(words)
for words in words:
    print (words, len (words))
print ("Number of words is", (numWords))

sentence = "The quick brown rhino jumped over the extremely lazy fox"
words =sentence.split()

wordLen = []
for i in words:
    wordLen=wordLen+[len(i)]
print(wordLen)


The 3
quick 5
brown 5
rhino 5
jumped 6
over 4
the 3
extremely 9
lazy 4
fox 3
Number of words is 10
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]


Expected Output:
```
The 3
quick 5
brown 5
rhino 5
jumped 6
over 4
the 3
extremely 9
lazy 4
fox 3
Number of words is 10
[3, 5, 5, 5, 6, 4, 3, 9, 4, 3]
```

### Problem 5

The string `addStr` contains numbers separated by a plus sign character (i.e. `+`).

Use an **accumulation pattern** to get the sum of all numbers in `addStr` and assign it to the variable `sumVal`. Print a line that contains `sumVal` and an appropriate label. 

Where appropriate, use the built-in **`split()`** function to split on `+`, and use **`int()`** to cast to an integer.

In [40]:
addStr = "2+5+10+20"
accum = addStr.split('+')

sumVal = 0
for w in accum:
    sumVal = sumVal + int(w)
print("The total of all numbers is", sumVal)


The total of all numbers is 37


Expected Output:</span><br/>
```
The total of all numbers is 37
```

### Problem 6

The string `weekTemps` contains a comma-separated list of temperatures (in degrees Fahrenheit).

Write code that computes the average temperature and assign it to the variable `avgTemp`.

The average temperature is defined as the total of all temperatures divided by the number of temperatures.

Do not hard-code your answer! This means that your code must compute both the total of all temperatures and the number of temperatures in `weekTemps`.

Print the variable `avgTemp` preceded by an appropriate label.

You need to use the built-in **`split()`** and **`float()`** functions, and **one** loop to solve this problem.

In [2]:
weekTemps = "75.1,77.7,83.2,82.5,81.0,79.5,85.7"
avgTemp = weekTemps.split(',')

accum = 0
for w in avgTemp:
    accum = accum + float(w)
print("The average temperature is", (accum/7))


The average temperature is 80.67142857142858


Expected Output:
```
The average temperature is 80.67142857142858
```

# Problem 7

The variable `rainfallMI` is a string that contains numbers that are separated by commas. Each number represents the monthly average rainfall (in inches) for Michigan.

Write code that does the following:
1. Compute the number of months that have more than 3 inches of rainfall. Store the result in the variable `numRainyMonths`.
2. Compute the total rainfall for all months.  Store the result in the variable `totRainfall`.
3. Print the variables `numRainyMonths` and `totRainfall` with the appropriate label as shown below.

In [50]:
rainfallMI = "1.65, 1.46, 2.05, 3.03, 3.35, 3.46, 2.83, 3.23, 3.5, 2.52, 2.8, 1.85"
totRainfall = rainfallMI.split(',')

rainfallMI_split = rainfallMI.split(",")
numRainyMonths = 0
for x in totRainfall:
    x = float(x)
    if x > 3.0:
        numRainyMonths += 1
print("Number of months with more than 3 inches of rain is", numRainyMonths)

accum = 0
numRainyMonths = 0
for w in totRainfall:
    accum = accum + float(w)
print("Total rainfall for all months is", accum)


Number of months with more than 3 inches of rain is 5
Total rainfall for all months is 31.73


Expected Output:
```
Number of months with more than 3 inches of rain is 5
Total rainfall for all months is 31.73
```

### Problem 8

The variable `sentence` holds a string of words. Write code that does the following:
1. Compute the number of words that begin and end with the same letter. This includes one-letter words. Store the result in the variable `sameLetterCount`.
2. Compute the number of words that contain an "f" or a "k".  Store the result in the variable `fkCount`.
3. Print the variables `sameLetterCount` and `fkCount` as shown below. 

You'll need to use the built-in **`split()`** function, the **`in`** operator to test for the existence of "f" or "k", and the **`or`** operator to join the logical expressions when testing for the existence of the letters. 

In [6]:
sentence = "students flock to the arb for a variety of outdoor activities such as jogging and picnicking"

sameLetterCount = 0
fkCount = 0
for d in sentence_split:
    if d[0] == d[-1]:
        sameLetterCount += 1
print("The number of words that begin and end with the same letter is", sameLetterCount)
for s in sentence.split():
    if ('f' in s or 'k' in s):
        fkCount += 1
print ("The number of words that contain f or k is", fkCount)

The number of words that begin and end with the same letter is 2
The number of words that contain f or k is 4


Expected Output:
```
The number of words that begin and end with the same letter is 2
The number of words that contain f or k is 4
```

### Problem 9

Write code that does the following:
1. Compute the number of words in variable `sentence` that contain either an "p" or an "g". Store the result in the variable `numPorG`.
2. Create a string `strPorG` composed of those words in `sentence` that contain an "p" or "g". Each word in `strPorG` must be separated by a comma.
3. Print the variables `numPorG` and `strPorG` as shown below.

Be careful not to double-count words that contain both `p` and `g`. Use the **in** operator to test for existence of the letters.

In [11]:
sentence = "python is a high level general purpose programming language that can be applied to many different classes of problems"

numPorG = 0
strPorG = ""
for s in sentence.split():
    if('p' in s or 'g' in s):
        numPorG += 1 
        strPorG += s + ','
print('Number of words containing p or g is', numPorG)
print('Those words are '+strPorG[:-1])
 

Number of words containing p or g is 8
Those words are python,high,general,purpose,programming,language,applied,problems


Expected Output:
```
Number of words containing p or g is 8
Those words are python,high,general,purpose,programming,language,applied,problems
```

### Problem 10

Write code that iterates over the list `months` and does the following:
1. Display elements from the list `months` and `rainfallMI` as a two column table as shown below.
2. Find the month with the highest rainfall and store its rainfall and month in variables named `maxRain` and `maxMonth`, respectively.
2. Find the month with the lowest rainfall and store its rainfall and month in variables named `minRain` and `minMonth`, respectively.
4. Calculate the total rainfall for the year and store the result in `totRain`.
5. Display variables in a manner that matches "Expected Output".

In the table, the "Month" column must be **left-justified** and "Rainfall" column must be **right-justified** though the use of string formatting.

Since you can only iterate over one sequence at a time, you will need to use an index to access items from the list `rainfallMI` as you iterate over the `months`, or vice versa. 

Finally, you must use only **one** for loop and only use syntax covered in the Learning Units to date.

In [106]:
rainfallMI = ['1.65', ' 1.46', ' 2.05', ' 3.03', ' 3.35', ' 3.46', ' 2.83', ' 3.23',
               ' 3.50', ' 2.52', ' 2.8', ' 1.85']
months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

maxRain = 0
minRain = 9999999
maxMonth = ''
minMonth = ''
totRain = 0
print ("Month \t Rainfall")
for i in range (len(months)):
    print (months[i], "\t", rainfallMI[i])
    if eval (rainfallMI[i]) > maxRain:
        maxRain = eval (rainfallMI[i])
        maxMonth = months [i]
    if eval (rainfallMI[i]) < minRain:
        minRain = eval (rainfallMI[i])
        minMonth = months[i]
    totRain += eval(rainfallMI[i])
print("The month with the largest rainfall is", maxMonth,"with a rainfall of", maxRain)
print("The month with the lowest rainfall is", minMonth, "with a rainfall of", minRain)
print("The annual rainfall is ", totRain)

Month 	 Rainfall
Jan 	 1.65
Feb 	  1.46
Mar 	  2.05
Apr 	  3.03
May 	  3.35
Jun 	  3.46
Jul 	  2.83
Aug 	  3.23
Sep 	  3.50
Oct 	  2.52
Nov 	  2.8
Dec 	  1.85
The month with the largest rainfall is Sep with a rainfall of 3.5
The month with the lowest rainfall is Feb with a rainfall of 1.46
The annual rainfall is  31.73


Expected Output:
```
Month   Rainfall
Jan         1.65
Feb         1.46
Mar         2.05
Apr         3.03
May         3.35
Jun         3.46
Jul         2.83
Aug         3.23
Sep         3.50
Oct         2.52
Nov         2.80
Dec         1.85
The month with the largest rainfall is Sep with a rainfall of 3.50
The month with the lowest rainfall is Feb with a rainfall of 1.46
The annual rainfall is 31.73
```

### <span style="color:dark green">Run the cells below to test your code</span>

In [7]:
import unittest

class PS03_01 (unittest.TestCase):
    def test_problem01(self):
        self.assertEqual(cntChars, 8)
class PS03_02 (unittest.TestCase):
    def test_problem02(self):
        self.assertEqual(cntList, 12)
class PS03_03 (unittest.TestCase):
    def test_problem03(self):
        self.assertEqual(numChars, 57)
        self.assertEqual(numVowels, 16)
class PS03_04 (unittest.TestCase):
    def test_problem04(self):
        self.assertEqual(numWords, 10)
        self.assertEqual(sum(wordLens), 47)
class PS03_05 (unittest.TestCase):
    def test_problem05(self):
        self.assertEqual(sumVal, 37)
class PS03_06 (unittest.TestCase):
    def test_problem06(self):
        self.assertEqual(round(avgTemp), 81)
class PS03_07 (unittest.TestCase):
    def test_problem07(self):
        self.assertEqual(numRainyMonths, 5)
        self.assertEqual(round(totRainfall), 32)
class PS03_08 (unittest.TestCase):
    def test_problem08(self):
        self.assertEqual(sameLetterCount, 2)
        self.assertEqual(fkCount, 4)
class PS03_09 (unittest.TestCase):
    def test_problem09(self):
        self.assertEqual(numPorG, 8)
        self.assertEqual(len(strPorG.split(',')), 8)
class PS03_10 (unittest.TestCase):
    def test_problem10(self):
        self.assertEqual(maxRain, 3.50)
        self.assertEqual(maxMonth, 'Sep')
        self.assertEqual(minRain, 1.46)
        self.assertEqual(minMonth, 'Feb')
        self.assertEqual(totRain, 31.73)

In [ ]:
unittest.main(argv=['first-arg-is-ignored'], exit=False, verbosity=2)