## <span style="color:blue">Problem Set 7</span>

### Problem 1

In no more than two (2) lines of code, use a **mutating method** to put the elements of the `animals` list into alphabetical order, and then print the last six (6) elements of the list.

Code is provided to display the list before and after it has been mutated.

In [34]:
# do not alter this code
animals = ['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', \
           'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', \
           'giraffe', 'goat', 'cow', 'tiger', 'bear']
print("original order:\n{}\n".format(animals))

# ## place your two lines of code below this line ... #####

animals.sort()
print("\nlast six, alphabetical:\n{}".format(animals[11:17]))

# ## ... and above this line ##############################

# do not alter the code below
print("\nalphabetical order:\n{}".format(animals))

original order:
['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear']


last six, alphabetical:
['otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']

alphabetical order:
['antelope', 'bear', 'cat', 'cow', 'deer', 'elephant', 'elk', 'giraffe', 'goat', 'minx', 'moose', 'otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']


<span style="color:blue">Expected Output:</span><br/>
```
original order:
['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear']

last six, alphabetical:
['otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']

alphabetical order:
['antelope', 'bear', 'cat', 'cow', 'deer', 'elephant', 'elk', 'giraffe', 'goat', 'minx', 'moose', 'otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']
```

### Problem 2

In one (1) line of code, use a **non-mutating** approach to print the last six (6) alphabetical elements from the `animals` list.

In [35]:
# do not alter this code
animals = ['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', \
           'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', \
           'giraffe', 'goat', 'cow', 'tiger', 'bear']
print("original order:{}\n".format(animals))

# ## place your one line of code below this line ... #####

print("last six, alphabetical:", sorted(animals)[11:17])

# ## ... and above this line #############################

# do not alter the code below
print("\noriginal order:{}".format(animals))

original order:['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear']

last six, alphabetical: ['otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']

original order:['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear']


<span style="color:blue">Expected Output:</span><br/>
```
original order:  ['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear'] 

last six, alphabetical: ['otter', 'rabbit', 'salamander', 'tiger', 'yak', 'zebra']

original order:  ['elephant', 'cat', 'moose', 'antelope', 'elk', 'rabbit', 'zebra', 'yak', 'salamander', 'deer', 'otter', 'minx', 'giraffe', 'goat', 'cow', 'tiger', 'bear']
 ```

### Problem 3

Write a for loop that iterates over `numList` and uses a **lambda** function to compute the square of each element. Print each element and its squared value with each iteration.

In [36]:
numList = [1,2,3]
# write your code below
sqr = 1
for i in range(len(numList)):
    sqr = numList[i]**2
    print ("The number is", numList[i], "and its square is",sqr)

The number is 1 and its square is 1
The number is 2 and its square is 4
The number is 3 and its square is 9


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The number is 1 and its square is 1<br />
The number is 2 and its square is 4<br />
The number is 3 and its square is 9<br /></span>

### Problem 4

Sort `numList` based on the [absolute value](https://en.wikipedia.org/wiki/Absolute_value) of each element..

Pass the list and a lambda function as parameters to the built-in **`sorted()`** function. Use the lambda function to return the absolute value for each list element, and use the built-in **`abs()`** function to get the absolute value.

In [38]:
numList = [1, -7, 4, -2, 3]
# write your code below

newList = []
newList = sorted(numList, key = lambda a: abs(a))
print(newList)

[1, -2, 3, 4, -7]


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
[1, -2, 3, 4, -7]</span>

### Problem 5

The `states` dictionary uses state name for keys, and values are the respective state population. Sort `states` on population and print the three highest-population states as well as the three lowest-population states.

In [39]:
states = {'Maine': 1335907, 'District of Columbia': 693972, 'Louisiana': 4684333, 
          'Tennessee': 6715984, 'New Jersey': 9005644, 'Arizona': 7016270, 
          'Alaska': 739795, 'South Dakota': 869666, 'Michigan': 9962311, 
          'Oregon': 4142776, 'Wyoming': 579315, 'Washington': 7405743, 
          'Florida': 20984400, 'Alabama': 4874747, 'Puerto Rico': 3337177, 
          'Montana': 1050493, 'Hawaii': 1427538, 'Mississippi': 2984100, 
          'Utah': 3101833, 'North Carolina': 10273419, 'Pennsylvania': 12805537, 
          'Massachusetts': 6859819, 'Idaho': 1716943, 'South Carolina': 5024369, 
          'North Dakota': 755393, 'Maryland': 6052177, 'New York': 19849399, 
          'Kansas': 2913123, 'Delaware': 961939, 'Nevada': 2998039, 
          'Minnesota': 5576606, 'Colorado': 5607154, 'New Hampshire': 1342795, 
          'Vermont': 623657, 'Wisconsin': 5795483, 'Missouri': 6113532, 
          'California': 39536653, 'Nebraska': 1920076, 'Georgia': 10429379, 
          'Iowa': 3145711, 'New Mexico': 2088070, 'Connecticut': 3588184, 
          'West Virginia': 1815857, 'Virginia': 8470020, 'Oklahoma': 3930864, 
          'Texas': 28304596, 'Illinois': 12802023, 'Rhode Island': 1059639, 
          'Ohio': 11658609, 'Indiana': 6666818, 'Kentucky': 4454189, 'Arkansas': 3004279}
# write your code below
sorted_states = sorted(states.items(), key=lambda x: x[1])
states_dict = dict(sorted_states)

states_list = list(states_dict)

lowest = [states_list[0], states_list[1], states_list[2]]

highest = [states_list[-1], states_list[-2], states_list[-3]]

print('Three lowest population states: ', lowest)
print('Three highest population states: ', highest)

Three lowest population states:  ['Wyoming', 'Vermont', 'District of Columbia']
Three highest population states:  ['California', 'Texas', 'Florida']


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
Three lowest population states: ['Wyoming', 'Vermont', 'District of Columbia']<br />
Three highest population states: ['California', 'Texas', 'Florida']</span>

### Problem 6

The `confections` dictionary's key-value pairs are candy name and price, respectively.

Use the built-in **`sorted()`** function, the **`.items()`** method, a **lambda function**, and **slice notation**, to make a list of tuples that contains the the 2nd, 3rd, and 4th most expensive confections. Assign this list to the variable `c234`.

It is possible to do this with one line of code, though it is not required.

In [40]:
confections = {'Coffee Crisp': 1.99, 'Eat-More': 1.59, 
               'Rockets': 0.55, 'Glosettes': 0.75, 
               'Wunderbar': 2.29, 'Big Turk': 1.89, 
               'Crispy Crunch': 1.79, 'Smarties': 0.95}

# write your code here
c234 = sorted(confections.items(), key = lambda x: x[1], reverse = True)[1:4]

# DO NOT change the code below
print("2nd, 3rd, 4th most expensive confections:\n", c234)

2nd, 3rd, 4th most expensive confections:
 [('Coffee Crisp', 1.99), ('Big Turk', 1.89), ('Crispy Crunch', 1.79)]


Expected Output:
```
2nd, 3rd, 4th most expensive confections:
 [('Coffee Crisp', 1.99), ('Big Turk', 1.89), ('Crispy Crunch', 1.79)]
```

### Problem 7

Using the same `confections` dictionary from the previous problem, complete the **`lessThan()`** function.

`lessThan()` accepts the parameters `priceDict` (a dictionary) and `amtMoney` (a floating point number) and returns a list of confections that are less than `amtMoney`.

Use a lambda function in `lessThan()` to determine which confections are less than `amtMoney`.

You may need to employ multiple lambda functions. The order of the returned list may be different than the "Expected Output", as long as the same elements are captured in the list.

In [41]:
def lessThan(priceDict, amtMoney=0):
    # complete the function
    confectionsList = map(lambda x: x[0], (filter(lambda x: x[1] < amtMoney, priceDict.items())))
    return list(confectionsList)

# DO NOT change the code below
amt = 1.55
confectionsList = lessThan(confections,amtMoney=amt)
print("Confections that cost lessThan ${} {} {}".format(amt ,":\n", confectionsList))

Confections that cost lessThan $1.55 :
 ['Rockets', 'Glosettes', 'Smarties']


Expected Output:
```
Confections that cost lessThan $ 1.55 :
 ['Rockets', 'Glosettes', 'Smarties']
```

### Problem 8

This is a variation of a problem from Problem Set 6. The `letter_values` dictionary maps each letter to its scrabble point value.

1. Complete the **`scrabbleValue()`** function such that it returns the Scrabble score of the word that it accepts as a parameter. In this function you need to accumulate the value of each of `word`'s letters.

2. Complete the **`bestScrabbleWords()`** function such that it returns a list of words that are sorted from highest to lowest score. The function's parameters are `words` (a list) and `howMany` (an integer). `howMany` determines the number of words that will be returned. You must use the built-in `sorted()` function and assign the key parameter to a lambda function to sort the list.

Using these functions, you must retrieve a list of the **five** (5) highest-scoring words from the `scrabbleWords` list. Display the list as shown in Expected Output.

In [42]:
def scrabbleValue(word):
    letter_values =  {'a':1, 'b':3, 'c':3, 'd':2, 'e':1, 'f':4, 'g': 2, 'h':4,
    'i':1, 'j':8, 'k':5, 'l':1, 'm':3, 'n':1, 'o':1, 'p':3, 'q':10, 'r':1,
    's':1, 't':1, 'u':1, 'v':8, 'w':4, 'x':8, 'y':4, 'z':10}
    # complete the function
    score = 0
    for cha in word.lower():
        score += letter_values[cha]
    return score

def bestScrabbleWords(words, howMany=3):
    # complete the function
    sortedWords = sorted(words, key=lambda word: scrabbleValue(word), reverse=True)
    return sortedWords[:howMany]

scrabbleWords = ['python', 'program', 'list', 'string', 'unix', 'hours', 'syntax', 'error']

# write your code below
bestWords = bestScrabbleWords(scrabbleWords, 5)
print(bestWords)

['syntax', 'python', 'program', 'unix', 'hours']


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
['syntax', 'python', 'program', 'unix', 'hours']</span>