## <span style="color:blue">Problem Set 8</span>

### <span style="color:red">Import Modules</span>
Before starting the assignment, run the cell below to import modules and read the data file. If you clear your kernel you will need to re-run this cell.

In [ ]:
import csv, json, random
from vincenty import latLngDistanceMeters

---

### <span style="color:red">umich_buildings.json</span>
The following questions will use the `umich_buildings.json` data file. Run the cell below to make data from the file available.

In [ ]:
fh = open('umich_buildings.json','r')
umich_buildings_str = fh.read()
umich_buildings = json.loads(umich_buildings_str)
fh.close()

The cell above creates the object `umich_buildings`, which is a list of dictionaries.

Each dictionary has the following keys:

| Key | Description |
| :--- | :----------------------------------- |
| address | street address |
| id | abbreviated building name |
| lat | geographic latitude |
| lng | geographic longitude |
| name | complete building name |

<br>This is an example of an item (i.e. a dictionary) from the `umich_buildings` list:
```
{'address': '1201 South Main Street Ann Arbor, MI 48104-3722', 'id': 'stadm', 'lat': 42.265071, 'lng': -83.748662, 'name': 'Michigan Stadium'}
```

### Problem 1

Write the function **`buildingLatLong()`** such that it checks if the parameter `building_id` matches the `id` key of one of the dictionaries in `umich_buildings`. If a match is found the function will return a tuple that contains `(name, lat, lng)` for the matching building, and will return **[None](https://www.w3schools.com/python/ref_keyword_none.asp)** if a match is not found.

Outside of the function, write code that iterates over `bldgs` and generates output that matches "Expected Output" below.

In [ ]:
bldgs = ['ccrb','aep','taubl','unknown','nq','stadm']

def buildingLatLong(building_id):
    # complete the function
    return

# write your code below


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
('Central Campus Recreation Building', 42.278866, -83.732666)<br/>
('Aerospace Engineering Lab Plasma Research', 42.293342, -83.710823)<br/>
('Alfred A Taubman Health Sciences Library', 42.28358, -83.734543)<br/>
None<br/>
('North Quadrangle', 42.280477, -83.740131)<br/>
('Michigan Stadium', 42.265071, -83.748662</span>

### Problem 2

**["Vincenty's formulae are two related iterative methods used in geodesy to calculate the distance between two points on the surface of a spheroid, developed by Thaddeus Vincenty"](https://en.wikipedia.org/wiki/Vincenty%27s_formulae)**

The **vincenty.py** module (imported in the first cell) provides the `latLngDistanceMeters()` function, which accepts two tuples as parameters (i.e. the latitude and longitude for a point), and returns the linear distance between those points in meters.

This is the syntax for the function (try it!):

```
latLngDistanceMeters( (42.3584, -71.0912), (42.278, -83.7382) )
```

In the cell below, complete the function **`buildingDistance()`** such that it accepts two building IDs and returns the linear distance between the two buildings.

Then, outside of the function, write code that iterates over the `bldgs` list, calls `buildingDistance()` for each tuple in the list, and prints the distance as shown in "Expected Output".

In [ ]:
bldgs = [('ccrb','aep'),('taubl','nq')]

def buildingDistance(bid_1, bid_2):
    # complete the function
    return

# write your code below


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The distance between CCRB and AEP buildings is 2414.80 meters<br />
The distance between TAUBL and NQ buildings is 575.54 meters </span>

### Problem 3

Write code that iterates over `umich_buildings`, finds the distance between each building and the **North Quadrangle**, then writes the results to a *CSV* file named _**north_quad_distance.csv**_. 

The file will have two columns: The first column will be the building's name, and the second column will be the linear distance between the building and North Quad (`"id": "nq"` in JSON file).

The header row (i.e. first row) identifies the column names. Column 1 will be "Name" and column 2 will be "Distance from North Quad". There should be one subsequent row for each building (including North Quadrangle, which should be zero meters away from itself). Round the distance to two decimal places.

Check your work by inspecting the .csv file in a text editor, then open it in a spreadsheet program like Excel or Google Sheets. In the text editor, strings should be quoted as shown in the example below. To achieve this, one approach is to use the optional parameters from the **[`csv.writer()`](https://docs.python.org/3/library/csv.html)** function.

In [ ]:
# write your code below


In a text editor, the first lines of your CSV file should be similar to this:  
```
"Name","Distance from North Quad"
"1000 Victors Way",4674.37
"1032 Greene Building",1498.65
"523 South Division Building",639.58
"Administrative Services Building",1410.47
```
(In a spreadsheet program the quotation marks may not be displayed)

---
### Run the cell below before attempting Problem 4

In [14]:
import csv, json, random  # JIC you've Restared & Cleared your kernel
baby_file = open('us-common-baby-names.csv','r')
baby_reader = csv.DictReader(baby_file)
baby_names = list(baby_reader) # turn the reader object into a proper list
baby_file.close()
random.shuffle(baby_names)

### Problem 4

Each item in the list `baby_names` (which was generated in the cell above from the `us-common-baby-names.csv` file) is a dictionary. Here's an example of an item from that list:

```
{'year': '1979', 'name': 'Leah', 'percent': '0.001786', 'sex': 'girl'}
```
             
The `percent` key holds a value which represents the percentage of babies born that year who were given the name found in the value of the `name` key.

In the cell below, complete the function **`findMostPopularName()`** such that it accepts the parameter `year` and returns the most popular name for that year along with the associated percent. The most popular name will be the one with the largest percentage for the specified `year`. The function will need to subset the `baby_names` list for the specified year, then determine the maximum `percent` for that year.

Outside of the function, write code that iterates over the `years` list and prints the most popular name for each year as shown in "Expected Output". Be sure to round percent to two decimal places.

In [23]:
years = ['1900', '1925', '1950', '1975', '2000'] 



def findMostPopularName(baby_names, year):
    maxper = -1 
    for i in range(len(baby_names)): 
        
        if baby_names[i]['year'] == year and maxper == -1: 
            maxper = i 
         
        if baby_names[i]['year'] == year and float(baby_names[i]['percent']) > float(baby_names[maxper]['percent']): 
            maxper = i 
    return baby_names[maxper]['name'], baby_names[maxper]['percent']  
     
for year in years: 
    n, p = findMostPopularName(baby_names, year) 
    print("Most popular name in " + year + " is " + n + " with " + str(round(float(p)*100, 2)) + " percent") 

# write your code below


Most popular name in 1900 is John with 6.06 percent
Most popular name in 1925 is Mary with 5.59 percent
Most popular name in 1950 is James with 4.73 percent
Most popular name in 1975 is Michael with 4.22 percent
Most popular name in 2000 is Jacob with 1.65 percent


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
Most popular name in 1900 is John at 6.06%<br/>
Most popular name in 1925 is Mary at 5.59%<br/>
Most popular name in 1950 is James at 4.73%<br/>
Most popular name in 1975 is Michael at 4.22%<br/>
Most popular name in 2000 is Jacob at 1.65%</span>

---
# Nested Data and Nested Iteration
Many web services return information in JSON format. Below is sample of JSON-formatted data returned by the Facebook API. In upcoming learning units you will be working with more complex nested data. The following problems serve as a warmup for future materials.

Run the cell below before proceeding to the problems that follow.

You may want to familiarize yourself with the data structure by examining it with https://jsoneditoronline.org/. Copy everyting after `fb_data = ` and paste it in the online editor.

In [ ]:
fb_data = {
 "data": [
  {
    "msg_id": "2253324325325123432madeup", 
    "from": {
      "id": "23243152523425madeup", 
      "name": "Jane Smith"
    }, 
    "to": {
      "data": [
        {
          "name": "Nested Data Problems", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "Practice your nested data parsing skills!!", 
    "type": "status", 
    "created_time": "2014-10-03T02:07:19+0000", 
    "updated_time": "2023-10-03T02:07:19+0000"
  }, 
 
  {
    "msg_id": "2359739457974250975madeup", 
    "from": {
      "id": "4363684063madeup", 
      "name": "John Smythe"
    }, 
    "to": {
      "data": [
        {
          "name": "Instant Pot Community", 
          "id": "432542543635453245madeup"
        }
      ]
    }, 
    "message": "Prepare meals faster.", 
    "type": "status", 
    "created_time": "2014-10-02T20:12:28+0000", 
    "updated_time": "2014-12-02T20:12:28+0000"
  }]
}

### Problem 5

For the first message, extract the values from `msg_id` and `message` into variables named `msg_id` and `first_message`, respectively. Print each variable.

<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
msg_id: 2253324325325123432madeup<br/>
text: Practice your nested data parsing skills!!</span>

### Problem 6

Extract the name of the author of the second post into a variable called `second_name`. Print `second_name`.

<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
John Smythe</span>

### Problem 7

Write code that retrieves the sender's name and id for each message in `fb_data` and uses it to construct a dictionary as shown in the Expected Output below.

<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
{'Jane Smith': '23243152523425madeup', 'John Smythe': '4363684063madeup'}</span>

### Problem 8

Write a function called **`fmtMsg()`** that accepts `m` as its only parameter. `m` is a dictionary that represents a single message (i.e. all associated attributes) as defined by the structure of `fb_data`. The function will generate neatly-formatted output and does not return an object.

After the function, write code to itererate through the messages in `fb_data` and use `fmtMsg()` to output the results as shown in "Expected Output".

In [ ]:
def fmtMsg(m):
    # complete the function here
    return None

# write your iteration code here


<span style="color:blue">Expected Output:</span><br/>
```
         msg_id : 2253324325325123432madeup
         sender : Jane Smith
             to : Nested Data Problems
  msg created @ : 2014-10-03T02:07:19+0000
  msg updated @ : 2023-10-03T02:07:19+0000
   message text : Practice your nested data parsing skills!!
         ------ : ------
         msg_id : 2359739457974250975madeup
         sender : John Smythe
             to : Instant Pot Community
  msg created @ : 2014-10-02T20:12:28+0000
  msg updated @ : 2014-12-02T20:12:28+0000
   message text : Prepare meals faster.
         ------ : ------
```