## <span style="color:blue">Problem Set 12</span>

### Problem 1

Write a **non-recursive function** called `power(num,exp)` where the `num` parameter is an integer that the function will raise to the power of the `exp` parameter, which is also an integer. The function will return the equivalent of `num ** exp`.

The function only needs to handle positive values for `num` or `exp`, and does not need to accommodate negative values.

You **must not** use `**` (the exponentiation operator), or any imported modules or functions.

In [15]:
# write your non-recursive function here
def power(num, exp):
    result = 1
    for i in range(exp):
        result *= num
    return result

In [16]:
# do not change the code below
# use it to test your function
print("1 to the 0th power is",power(1,0))
print("1 to the 1st power is",power(1,1))
print("2 to the 0th power is",power(2,0))
print("2 to the 1st power is",power(2,1))
print("2 to the 8th power is",power(2,8))
print("2 to the 15th power is",power(2,15))

1 to the 0th power is 1
1 to the 1st power is 1
2 to the 0th power is 1
2 to the 1st power is 2
2 to the 8th power is 256
2 to the 15th power is 32768


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
1 to the 0th power is 1<br />
1 to the 1st power is 1<br />
2 to the 0th power is 1<br />
2 to the 1st power is 2<br />
2 to the 8th power is 256<br />
2 to the 15th power is 32768</span>

### Problem 2

Write a **recursive function** called `power(num,exp)` where the `num` parameter is an integer that the function will raise to the power of the `exp` parameter, which is also an integer. The function will return the equivalent of `num ** exp`.

The function only needs to handle positive values for `num` or `exp`, and does not need to accommodate negative values.

You **must not** use `**` (the exponentiation operator), or any imported modules or functions.

In [ ]:
# write your recursive function here
def power(num,exp):
    if exp == 0:
        return 1
    return num * power(num,exp-1)

In [ ]:
# do not change the code below
# use it to test your function
print("1 to the 0th power is",power(1,0))
print("1 to the 1st power is",power(1,1))
print("2 to the 0th power is",power(2,0))
print("2 to the 1st power is",power(2,1))
print("2 to the 8th power is",power(2,8))
print("2 to the 15th power is",power(2,15))

<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
1 to the 0th power is 1<br />
1 to the 1st power is 1<br />
2 to the 0th power is 1<br />
2 to the 1st power is 2<br />
2 to the 8th power is 256<br />
2 to the 15th power is 32768</span>

### Problem 3

Write a **recursive function** named `reverse_string(s)`. The function accepts a string `s` as a parameter and returns a string that is the reverse order of `s`, as shown in 'Expected Output'. 

The only Python function required is `len()`. Do not use any other python functions or methods.

In [9]:
# write your recursive function here
def reverse_string(s):
    if len(s) == 0:
        return s
    else:
        return reverse_string(s[1:]) + s[0]

In [10]:
# do not change the code below
# use it to test your function
string_to_reverse = "the quick brown fox jumps over the lazy dog"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))
print()
string_to_reverse = "able was I ere I saw elba"
print("The original string:",string_to_reverse)
print("The reversed string:",reverse_string(string_to_reverse))

The original string: the quick brown fox jumps over the lazy dog
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht

The original string: able was I ere I saw elba
The reversed string: able was I ere I saw elba


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The original string: the quick brown fox jumps over the lazy dog<br />
The reversed string: god yzal eht revo spmuj xof nworb kciuq eht<br />
<br />
The original string: able was I ere I saw elba<br />
The reversed string: able was I ere I saw elba</span>   

### Problem 4

Write the **recursive function** `reverse_list(lst)` such that it accepts a list named `lst` as a parameter and returns a reverse-orders version of `lst`, as shown in 'Expected Output'.

The only python function required is `len()`. Do not use any other python functions or methods.

Hint: The expression `list1 + list2` creates a new list consisting of `list2` appended to `list1`.

In [11]:
# write your recursive function here
def reverse_list(lst):
    if not lst: return []
    return [lst.pop()]+ reverse_list(lst)

In [12]:
# do not change the code below
# use it to test your function
list_to_reverse = [1,2,3,4,5,6,7,8,9,0]
print("The original list:",list_to_reverse)
print("The reversed list:",reverse_list(list_to_reverse))

The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]<br />
The reversed list: [0, 9, 8, 7, 6, 5, 4, 3, 2, 1]</span>  

### Problem 5

Write a **recursive function** named `totalDigits(n)` where `n` is an integer number. The function will return the sum of all the digits in `n`.

In [7]:
# write your function below
def totalDigits(n):
    x = 0
    for i in str(m):
        x += int(i)
    return x

In [8]:
# do not change the code below
# use it to test your function
for m in [111,222,333,1076458]:
    print("The total of the digits in",m,"is",totalDigits(m))

The total of the digits in 111 is 3
The total of the digits in 222 is 6
The total of the digits in 333 is 9
The total of the digits in 1076458 is 31


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The total of the digits in 111 is 3<br/>
The total of the digits in 222 is 6<br/>
The total of the digits in 333 is 9<br/>
The total of the digits in 1076458 is 31</span>  

### Problem 6

Given the parameter `binNum` (which is a string that represents a binary number), write a **recursive function** named `convertToDecimal(binNum)` such that it returns the decimal number equivalent of `binNum` (i.e. an integer).

The function must work for a binary number of any length, so **do not hardcode** position values. Position values must be determined within the function.

Assume that a valid binary number is passed (i.e. no error checking is required). Because the binary number passed to the function is a string, you will need to coerce each binary digit into an integer using the built-in `int()` function.

The values for respective positions in a binary number are:
   
            2**n  2**(n-1) ... 2**3  2**2  2**1  2**0

            ....  .......  ...    8     4     2     1 

To determine the decimal number equivalent of a binary number:
  1. For each binary digit, multiply the binary digit by the value of its position.
  2. Repeat step one for all digits in the binary number sequence.
  3. Add all the results together.

The [Counting in binary](https://en.wikipedia.org/wiki/Binary_number#Counting_in_binary) section of Wikipedia's article on binary numbers explains how binary numbers can represent base 10 (i.e. decimal) numeric values.

This [binary to decimal calculator](https://www.rapidtables.com/convert/number/binary-to-decimal.html) may be useful for testing your algorithm.

In [13]:
# write your recursive function here
def convertToDecimal(binNum):
    if len(binNum) == 0:
        return 0
    else:
        return convertToDecimal(binNum[:-1]) * 2 + int(binNum[-1])

In [14]:
# do not change the code below
# use it to test your function
for b in ['11111111','10101010','010101','10101']:
    print("The binary number",b,"is",convertToDecimal(b),"in decimal")

The binary number 11111111 is 255 in decimal
The binary number 10101010 is 170 in decimal
The binary number 010101 is 21 in decimal
The binary number 10101 is 21 in decimal


<span style="color:blue">Expected Output:</span><br/>
<span style="font: courier; font-size: 13px">
The binary number 11111111 is 255 in decimal<br />
The binary number 10101010 is 170 in decimal<br />
The binary number 010101 is 21 in decimal<br />
The binary number 10101 is 21 in decimal</span>  